# Generated by Django 3.2 on 2022-09-07 16:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('images', django_mysql.models.ListCharField(models.CharField(max_length=255), max_length=512, size=2)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
