# Generated by Django 3.2 on 2022-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_update_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
