# Generated by Django 3.2 on 2022-09-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_update_at_product_updated_at'),
        ('order', '0002_rename_customer_order_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.product'),
        ),
    ]
